# Generated by Django 3.0.2 on 2020-11-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=120)),
                ('NoIdentitas', models.CharField(max_length=120)),
                ('NIK', models.DecimalField(decimal_places=0, max_digits=1000000000)),
                ('email', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=20)),
                ('Telepon', models.CharField(max_length=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
